### PR TITLE
#[allow(where_clauses_object_safety)] in src/lib.rs

### PR DESCRIPTION
**Pull request by andrewpollack**
Issue: #150 

Resolution for allow until lint is either turned error, or lint is resolved

### CODE REVIEW

**Comment by joshlf** [comment]
Thanks for this, @andrewpollack! It looks good; is there a reason you closed it?

**Comment by joshlf** [comment]
Thanks for this, @andrewpollack! It looks good; is there a reason you closed it?

**Comment by joshlf** [comment]
Thanks for this, @andrewpollack! It looks good; is there a reason you closed it?

**Comment by andrewpollack** [comment]
@joshlf introducing the `allow` wasn't successfully resolving the warning. The `allow` seemingly needs to be placed where the trait object is created, even though the lint is firing on the trait definition (i.e. where the crate is being used, as opposed to the source itself). I closed the PR since I wasn't successful in repressing the warning

https://github.com/rust-lang/rust/issues/102546 captures this as well

**Comment by andrewpollack** [comment]
That said, if there's another way I can approach to resolve this, I'd be happy to do so! For the time being, we're holding off on changes in our codebase firing from this lint until upstream discussions settle down (see comment threads on https://github.com/rust-lang/rust/issues/106247 )

**Comment by joshlf** [comment]
Ah got it, thanks for the clarification! I likely won't have time to work on this for the next few weeks, but I've marked [your issue](https://github.com/google/zerocopy/issues/150) as a release blocker for 0.7.0, so it'll get resolved before that release.

**Comment by andrewpollack** [comment]
Awesome, thank you @joshlf!

**Comment by joshlf** [comment]
np!

**Pull request closed without merging**
