### PR TITLE
Renamed `as_bytes_mut` to `as_mut_bytes`

### LINKED ISSUE #253: Consider renaming `as_bytes_mut` to `as_mut_bytes`
This would be consistent with the naming convention used elsewhere in the ecosystem such as in [`Vec::as_mut_slice`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.as_mut_slice). We also should do this for any other similarly-named methods/functions.

### PR DESCRIPTION
**Pull request by dorryspears**
Closes #253 

I saw this in the nice-to-haves in #671, so I thought I would knock it out.

### CODE REVIEW

**Review by jswrenn — CHANGES_REQUESTED** [review]
Can you just edit your commit message to:
```
Renamed `as_bytes_mut` to `as_mut_bytes`
```

**Comment by dorryspears** [comment]
@jswrenn Renamed commit

**Comment by jswrenn** [comment]
Whoops, sorry for the inconvenience, but I didn't mean for you to edit out the reference to the issue. The full message should be something like this:
```
Renamed `as_bytes_mut` to `as_mut_bytes`

Fixes #253
```

**Comment by joshlf** [comment]
> Whoops, sorry for the inconvenience, but I didn't mean for you to edit out the reference to the issue. The full message should be something like this:
> 
> ```
> Renamed `as_bytes_mut` to `as_mut_bytes`
> 
> Fixes #253
> ```

...and if you want to be *really* pedantic with [our commit message guidelines](https://github.com/google/zerocopy/blob/main/CONTRIBUTING.md#commit-messages), it should be "Rename `as_bytes_mut`..." rather than "Renamed `as_bytes_mut`..." (past tense). To be clear, we will absolutely still merge this without that tiny change, but while we're nitpicking 😛

**Comment by dorryspears** [comment]
@jswrenn @joshlf I appreciate the guidance, I am new to zerocopy, learning the ways 🎉
Changed commit message to include the issue and reflect the grammar from the guidelines

**Comment by jswrenn** [comment]
One last tweak: Just put a double newline between the subject and 'Fixes', like this:
```
Renamed `as_bytes_mut` to `as_mut_bytes`

Fixes #253
```
Right now, they're all on one line.

**Comment by jswrenn** [comment]
We do this because git treats the first line of the commit message as its subject; see here: https://github.com/google/zerocopy/commit/bff9148ad8e7bf034e0992a1f8b4bf9553f2e386.patch

**Comment by dorryspears** [comment]
@jswrenn fixed commit message

**Comment by joshlf** [comment]
Thanks for this, @dorryspears !

**Pull request merged**
