### PR TITLE
[byteorder] Implement additional ops for native RHSs

### PR DESCRIPTION
**Pull request by jswrenn**

### CODE REVIEW

**Comment by joshlf** [comment]
My plan is to not do the array impls in this PR, but follow up in #1749.

**Comment by jswrenn** [comment]
LGTM!

**Review by joshlf — APPROVED** [review]

**Comment by joshlf** [comment]
> I'm testing this to confirm that it doesn't cause inference issues for Fuchsia in https://fxrev.dev/1127272.

This has landed successfully.

**Comment by jswrenn** [comment]
Wahoo!

**Pull request merged**
