### PR TITLE
Inline TryFromBytes derive for variant structs

### PR DESCRIPTION
**Pull request by djkoloski**
I didn't update the goldens because it was too hard

### CODE REVIEW

**Comment by jswrenn** [comment]
The goldens?

**Comment by djkoloski** [comment]
The derive macro output tests (I call them goldens because they're effectively golden files)

**Comment by jswrenn** [comment]
> I didn't update the goldens because it was too hard

@joshlf Told ya so. 😛 We *really* need to make updating these as easy as `TRYBUILD=overwrite`.

**Comment by joshlf** [comment]
> > I didn't update the goldens because it was too hard
> 
> 
> 
> @joshlf Told ya so. 😛 We *really* need to make updating these as easy as `TRYBUILD=overwrite`.

My hope is that https://github.com/google/zerocopy/pull/1711 will make this much less painful.

**Review by joshlf — APPROVED** [review]

**Comment by joshlf** [comment]
> I didn't update the goldens because it was too hard

Updated them and pushed.

**Pull request merged**
